### ISSUE TITLE
Support for custom resources

### ISSUE THREAD

**Issue by montmanu** [ahmetb/kubectl-aliases#1]
This is great. Thank you for sharing! Any ideas about adding support for custom resources? 

Something along the lines of:

```bash
kubectl get crd -o json | jq '[.items[].spec.names] | map([.kind,.singular,.plural, ["g","d","rm"], null])'
```

would get pretty close to the shape already being used:

https://github.com/ahmetb/kubectl-aliases/blob/0533366d8e3e3b3987cc1b7b07a7e8fcfb69f93c/generate_aliases.py#L42-L51

However, seems this would be tricky without an abbreviation field defined in the `spec.names`.. I'm happy regenerating locally after manually adding my own abbreviations, but maybe you have some ideas about how to support this more generally?

**Comment by ahmetb** [comment]
@montmanu ahh, CRDs would be tricky, especially because we can't make them work for everyone and we statically generate the aliases. I'd say this is a WONTFIX for now, mostly because we don't even have shorthands for lots of other native Resource Types (like NetworkPolicy, ClusterRole[Binding], Role, Job, CronJob, StatefulSet, PersistentVolume[Claim] etc).
