### ISSUE TITLE
Problem using the aliases with the `watch` command

### ISSUE THREAD

**Issue by vharsh** [ahmetb/kubectl-aliases#12]
Hi I recently started using your awesome aliases and I really like using them. :clinking_glasses:  
I am facing problem using it with the `watch` command.

I run `Ubuntu18.04`

```bash
$ watch --version
watch from procps-ng 3.3.12
```

This works as expected.

```bash
$ watch kubectl get pods
# works as expected
```

This doesn't.
```bash
$ watch kgpo
sh: 1: kgpo: not found

```
I am not sure if you and others also face this issue.
If you have a work-around please share below. :bowing_man:

**Comment by ahmetb** [comment]
This is expected, because `kgpo` is a bash alias and not a program. When bash makes your operating system an execve call like:

    execve(watch, [kgpo])

and when watch makes a call like `execve(kgpo)`, your OS won't know about such a program in the PATH.

This is true for any program. Try doing this:

```sh
alias slp='sleep 100'
bash
watch slp
```

**Comment by ahmetb** [comment]
That said I've been meaning to move `--watch` to the beginning. For example:

    alias kgpow='kubectl get pods --watch'

today but I want it to be

    alias kgpow='watch kubectl get pods'

because honestly kubectl's watch kinda sucks, I never understood how it works. 

What's preventing me from making this change is that the way I designed the generator script. But it can be added as a post-replace hack.
