### ISSUE TITLE
`function kubectl()` in README doesn't handle quoted arguments correctly

### ISSUE THREAD

**Issue by axesilo** [ahmetb/kubectl-aliases#23]
I posted on Stack Overflow about a difficult-to-diagnose error when working with `kubectl` here: https://stackoverflow.com/questions/54948471/jsonpath-range-not-working-when-using-kubectl

I traced the error down to having followed this repo's suggestion to overwrite kubectl with a function.  It seems the function strips quotes from arguments when in some cases they are necessary.

Instead of

```sh
function kubectl() { echo "+ kubectl $@"; command kubectl $@; }
```

how about this?

```sh
function kubectl() { echo "+ kubectl $@"; command kubectl "$@"; }
```

**Comment by ahmetb** [comment]
I recall that wasnt working under certain circumstances but that’s what shellcheck was recommending, too. 

If you tested thoroughly, I’m happy to accept a PR.

**Comment by RossWhitehead** [comment]
The issue is further complicated with commands such as this -
`kubectl -n istio-system port-forward $(kubectl -n istio-system get pod -l app=prometheus -o jsonpath='{.items[0].metadata.name}') 9090:9090`

results in...
`+ kubectl -n istio-system port-forward + kubectl -n istio-system get pod -l app=prometheus -o jsonpath={.items[0].metadata.name} prometheus-67599bf55b-sq822 9090:9090
Error: unknown shorthand flag: 'l' in -l`

Not sure what the fix is. I'd recommend removing the function from the README.

BTW ahmetb. Great project. The aliases are really useful. Many thanks for your efforts.

**Comment by ahmetb** [comment]
Since it’s just in the readme and not in the code, I am ok with keeping it despite it half-works. I’d be interesting in figuring out what the actual fix would be though. 

“$@“ should be working. Have you tried it @RossWhitehead?
