### ISSUE TITLE
Add --show-labels for nodes, configmaps and other resources.

### ISSUE THREAD

**Issue by murarisumit** [ahmetb/kubectl-aliases#36]
Show labels as i see is for pods and deployment only. 

```
('sl', '--show-labels', ['g'], ['oyaml', 'ojson']
         + diff(res_types, ['po', 'dep'])),
```

I'm able to write: `kgsl nodes` but not `kgnosl` or `kgslno` same for configmaps and other k8s objects.

If there any reason for us to not add them other resources, can we add them up too

**Comment by ahmetb** [comment]
This is mainly an optimization to reduce number of rarely used aliases generated.
I strongly encourage you make a fork and re-generate this for your use case.
I tend to think people don't use labels as much for ConfigMaps etc. :) Nodes have labels by default and Pods do, too. That's why it is the way it is.
